// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: timeMemorizer.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Category) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Category) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AddTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *AddTimeRequest) Reset() {
	*x = AddTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTimeRequest) ProtoMessage() {}

func (x *AddTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTimeRequest.ProtoReflect.Descriptor instead.
func (*AddTimeRequest) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{1}
}

func (x *AddTimeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AddTimeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddTimeRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *AddTimeResponse) Reset() {
	*x = AddTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTimeResponse) ProtoMessage() {}

func (x *AddTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTimeResponse.ProtoReflect.Descriptor instead.
func (*AddTimeResponse) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{2}
}

func (x *AddTimeResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type SubtractTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SubtractTimeRequest) Reset() {
	*x = SubtractTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractTimeRequest) ProtoMessage() {}

func (x *SubtractTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractTimeRequest.ProtoReflect.Descriptor instead.
func (*SubtractTimeRequest) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{3}
}

func (x *SubtractTimeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SubtractTimeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubtractTimeRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SubtractTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *SubtractTimeResponse) Reset() {
	*x = SubtractTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubtractTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtractTimeResponse) ProtoMessage() {}

func (x *SubtractTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtractTimeResponse.ProtoReflect.Descriptor instead.
func (*SubtractTimeResponse) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{4}
}

func (x *SubtractTimeResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ShowTimeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ShowTimeRequest) Reset() {
	*x = ShowTimeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTimeRequest) ProtoMessage() {}

func (x *ShowTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTimeRequest.ProtoReflect.Descriptor instead.
func (*ShowTimeRequest) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{5}
}

func (x *ShowTimeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ShowTimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
}

func (x *ShowTimeResponse) Reset() {
	*x = ShowTimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timeMemorizer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowTimeResponse) ProtoMessage() {}

func (x *ShowTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timeMemorizer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowTimeResponse.ProtoReflect.Descriptor instead.
func (*ShowTimeResponse) Descriptor() ([]byte, []int) {
	return file_timeMemorizer_proto_rawDescGZIP(), []int{6}
}

func (x *ShowTimeResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_timeMemorizer_proto protoreflect.FileDescriptor

var file_timeMemorizer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x22, 0x5f, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x3d, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x22, 0x2d, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x3d, 0x0a, 0x10, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x32,
	0xb2, 0x01, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x72, 0x12, 0x2e, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0f, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x41, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3e, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x14, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x53, 0x75, 0x62, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x31, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x2e,
	0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timeMemorizer_proto_rawDescOnce sync.Once
	file_timeMemorizer_proto_rawDescData = file_timeMemorizer_proto_rawDesc
)

func file_timeMemorizer_proto_rawDescGZIP() []byte {
	file_timeMemorizer_proto_rawDescOnce.Do(func() {
		file_timeMemorizer_proto_rawDescData = protoimpl.X.CompressGZIP(file_timeMemorizer_proto_rawDescData)
	})
	return file_timeMemorizer_proto_rawDescData
}

var file_timeMemorizer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_timeMemorizer_proto_goTypes = []interface{}{
	(*Category)(nil),             // 0: Category
	(*AddTimeRequest)(nil),       // 1: AddTimeRequest
	(*AddTimeResponse)(nil),      // 2: AddTimeResponse
	(*SubtractTimeRequest)(nil),  // 3: SubtractTimeRequest
	(*SubtractTimeResponse)(nil), // 4: SubtractTimeResponse
	(*ShowTimeRequest)(nil),      // 5: ShowTimeRequest
	(*ShowTimeResponse)(nil),     // 6: ShowTimeResponse
}
var file_timeMemorizer_proto_depIdxs = []int32{
	0, // 0: AddTimeResponse.category:type_name -> Category
	0, // 1: SubtractTimeResponse.category:type_name -> Category
	0, // 2: ShowTimeResponse.categories:type_name -> Category
	1, // 3: TimeMemorizer.AddTime:input_type -> AddTimeRequest
	3, // 4: TimeMemorizer.SubstractTime:input_type -> SubtractTimeRequest
	5, // 5: TimeMemorizer.ShowTime:input_type -> ShowTimeRequest
	2, // 6: TimeMemorizer.AddTime:output_type -> AddTimeResponse
	4, // 7: TimeMemorizer.SubstractTime:output_type -> SubtractTimeResponse
	6, // 8: TimeMemorizer.ShowTime:output_type -> ShowTimeResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_timeMemorizer_proto_init() }
func file_timeMemorizer_proto_init() {
	if File_timeMemorizer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timeMemorizer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubtractTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowTimeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_timeMemorizer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowTimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timeMemorizer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timeMemorizer_proto_goTypes,
		DependencyIndexes: file_timeMemorizer_proto_depIdxs,
		MessageInfos:      file_timeMemorizer_proto_msgTypes,
	}.Build()
	File_timeMemorizer_proto = out.File
	file_timeMemorizer_proto_rawDesc = nil
	file_timeMemorizer_proto_goTypes = nil
	file_timeMemorizer_proto_depIdxs = nil
}
